### ISSUE TITLE
Touchs

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#65] opened 2015-01-19 04:19 UTC
http://gyazo.com/aa5450526e647bf1b9a9456abb6e6ba2

In DTC/M the touchs are turned/inverted. 

*A blue player can see the red team touchs but not the own team touchs.

**Comment by iEli2tyree011** [comment] 2015-01-19 04:20
I'll look into this, thanks.

**Comment by iEli2tyree011** [comment] 2015-01-19 04:22
This has already been fixed as of #64. Please recompile the plugin and if the problem is still there, please reopen.

**Closed by iEli2tyree011** 2015-01-19 04:22 UTC

**Comment by Alfalik** [comment] 2015-01-19 04:29
Fixed
