### ISSUE TITLE
Observers not being able to open written books

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#319] opened 2015-03-01 16:24 UTC
The most obvious example would be the "comming soon" book.
Version: 1.0-SNAPSHOT-git-CardinalPGM-cdb3974

**Comment by elespawol** [comment] 2015-03-01 16:26
Is because the book is empy
El dia 01/03/2015 17.24, "Eudaldca" <notifications@github.com> va escriure:

**Comment by Eudaldca** [comment] 2015-03-01 16:28
@elespawol I gave myself via /give a written book that wasn't empty and I couldn't open it either.

**Comment by twizmwazin** [comment] 2015-03-01 16:29
dupe of #295

**Closed by twizmwazin** 2015-03-01 16:29 UTC
Labels: duplicate
