### ISSUE TITLE
Regions not working correctly in GDIII

### ISSUE THREAD

**Issue by Eudaldca** [twizmwazin/CardinalPGM#548] opened 2015-04-05 10:05 UTC
In golden drought 3, you cannot buid next to your woolrooms, as well as not being able to break gold blocks in your base. The message it prints to you is "You cannot build outside the map area!", so the issue is related to this somehow.
My cardinal version is the latest up to the time this post has been created, and the xml of the map is the one from maps.oc.tc.

**Comment by CaptainElliott** [comment] 2015-04-05 10:12
This will be to do with the xml, make sure that the regions match the map 
most likely dupe of https://github.com/twizmwazin/CardinalPGM/issues/492

**Comment by Eudaldca** [comment] 2015-04-05 10:20
@CaptainElliott You however cannot enter your own wool room, so that is fixed. It is also not an issue of the map being incorrectly positioned, as it happens in both lanes equally.

**Comment by SungMatt** [comment] 2015-04-05 11:37
@Eudaldca As I have said in the other thread, this is due to a difference between the map and the xml on Reshif's site, and is not a plugin error. This issue tracker is meant for CardinalPGM bugs, not as a duplicate of the official PGM bug tracker, or a map error tracker.

**Comment by iEli2tyree011** [comment] 2015-04-05 16:29
@Eudaldca Make sure you didn't get rid of block 36. The map has a ton of regions based on block 36.

**Comment by Eudaldca** [comment] 2015-04-05 16:30
@iEli2tyree011 Oh, but blocks 36 are no longer in mc 1.8? I did get rid of them, because they caused fps lag like crazy.

**Comment by iEli2tyree011** [comment] 2015-04-05 17:46
They are still necessary to have regions work correctly for the map. We may look for a way to be able to hide block 36 from the client, so it doesn't cause as  much lag.

**Closed by iEli2tyree011** 2015-04-05 17:46 UTC
Labels: duplicate
