### ISSUE TITLE
A touch message appear when the objective is completed

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#202] opened 2015-02-18 19:49 UTC
Video: http://youtu.be/VvgVANqUVak
Cardinal Version: http://gyazo.com/f63e2a48cf132718da49d21f0830265b

**Comment by twizmwazin** [comment] 2015-02-18 19:56
I'll look into this

**Comment by AngelCasillas01** [comment] 2015-02-18 19:57
Please put "A touch message appear when the objective is completed" that title that you put is very confused :C

**Comment by TiTo-418** [comment] 2015-02-18 20:17
And the obs cant view the touch message

**Comment by elespawol** [comment] 2015-02-18 21:05
I think thats not a bug.
El dia 18/02/2015 21.17, "TiTo-418" <notifications@github.com> va escriure:

**Comment by AngelCasillas01** [comment] 2015-02-18 22:05
I don't have the problem when you are join, otherwise the obs problem its true

**Comment by iEli2tyree011** [comment] 2015-02-18 23:36
Fixed in 767ac10d0f7fe72047c1dc9dc2fa786ea01e5302

**Closed by iEli2tyree011** 2015-02-18 23:36 UTC
