### ISSUE TITLE
(BUG) Moderator permissions

### ISSUE THREAD

**Issue by GChevy** [twizmwazin/CardinalPGM#272] opened 2015-02-25 23:24 UTC
https://www.youtube.com/watch?v=Bw_rRStMYz8

**Comment by CaptainElliott** [comment] 2015-02-25 23:29
Could you please make the video available for mobile :)

**Comment by CaptainElliott** [comment] 2015-02-25 23:37
Please give more description if what the issue is, as the video was poor quality for me (I'm on mobile) I can't see that chat, I assume the issue is that you don't have the perms after you have been given mod position. For the permissions to update you need to relog. Does that fix your issue ?

**Comment by Alfalik** [comment] 2015-02-26 00:10
The video clearly said "You are no longer a Moderator!", then you try commands like gamemode 1 or start, I don´t understand what do you mean with the issue.

**Comment by RubeGamerV** [comment] 2015-02-26 02:18
Mods can punish someone

**Comment by twizmwazin** [comment] 2015-02-28 17:21
Closing in favor of #293

**Closed by twizmwazin** 2015-02-28 17:21 UTC
