### ISSUE TITLE
Cardinal/database.xml: Premature end of file.

### ISSUE THREAD

**Issue by ghost** [twizmwazin/CardinalPGM#839] opened 2015-08-20 09:08 UTC
the plugin doesn't want to load due an error with the database.xml

log: http://pastebin.com/itJzpD9a

deleting the database.xml does solve the problem, but this problem occurred multiple times, with multiple versions of cardinal.

**Comment by SungMatt** [comment] 2015-08-20 10:03
Could you post your database.xml too?

**Comment by kroest** [comment] 2015-08-20 10:52
@SungMatt  the database file is empty, i think that is the problem. i didnt wipe it. when i removed the file and rebooted it, it did had data in it, and the plugin did load. for some reason the plugin wipes the database.xml causing it to not load after a reboot.

**Comment by twizmwazin** [comment] 2015-08-20 16:55
How do you shut your server down?

**Comment by kroest** [comment] 2015-08-20 17:05
i didnt shut my server down, it propably crashed, but it wont be easy to find the logs of that crash since i was away for 3 days.

when i shut my server down, i use /stop or the stop option in the multicraft control panel.

**Comment by twizmwazin** [comment] 2015-08-20 17:18
If it crashes there is nothing I can do but have the plugin delete the database. Perhaps a backup system could be integrated. Anyone want to do this?

**Comment by twizmwazin** [comment] 2015-09-08 22:12
Closing as this doesn't seem to be easily reproducible.

**Closed by twizmwazin** 2015-09-08 22:12 UTC
