### ISSUE TITLE
Pistons Issue

### ISSUE THREAD

**Issue by knightopress** [twizmwazin/CardinalPGM#559] opened 2015-04-06 15:52 UTC
You can bypass the build height limit of any map with pistons, video example below. I'm pretty sure there are piston "push" and "pull" events in Bukkit that you can cancel under an "if" statement.

https://youtu.be/p9YSos6w7ZU

**Comment by CaptainElliott** [comment] 2015-04-06 15:55
I don't really think this is too an issue, the piston should not push if it had a block on it

**Comment by knightopress** [comment] 2015-04-06 16:04
Seems like pistons can bypass any type of region limits, not just height.

**Comment by MrTheSharpie** [comment] 2015-04-06 16:08
Also happens if you push blocks to a void region

**Comment by knightopress** [comment] 2015-04-06 16:11
Yeah this appears to happen with any type of region limit. What's weird is that I did find code to cancel piston events when they interact with a region limited area, but the code doesn't seem to work.

**Comment by iEli2tyree011** [comment] 2015-04-06 21:55
I'll check the code for it over later tonight and I'll also make sure that it is also prevented in block regions.

**Comment by TiTo-418** [comment] 2015-04-07 01:07
Dupe of https://github.com/twizmwazin/CardinalPGM/issues/556 ???

**Comment by iEli2tyree011** [comment] 2015-04-07 04:39
@TiTo-418 How is that a duplicate by any means?

**Comment by dentmaged** [comment] 2015-04-07 06:06
They both are to do with regions and the height limit, but #556 is to do with doors, not pistons.

**Comment by TiTo-418** [comment] 2015-04-07 06:11
You can add fences, trap doors, etc..., all the block with has (on can has in a variant, like trap doors or pistons) more than one block of colision box.

**Comment by knightopress** [comment] 2015-04-07 11:10
No, #556 has to do with the player interaction of two block high blocks. This has to do with the piston interaction between the piston itself and other blocks it pushes.

**Closed** 2015-04-09 17:04 UTC
Labels: bug

**Comment by TiTo-418** [comment] 2015-05-21 04:27
@iEli2tyree011 This isn't fixed with the void regions
