### ISSUE TITLE
Some XML Errors?

### ISSUE THREAD

**Issue by Ambamore2000** [twizmwazin/CardinalPGM#172] opened 2015-02-14 15:19 UTC
Some maps don't work, assuming it's the XML, it shows that the author is null, when it is supposed to be from a UUID. Secondly, when the map tries to cycle, it doesn't work, and yeah.

Here are some XML files that don't work:
Ozone - http://pastebin.com/PKtUMaBf
Cloud Nine - http://pastebin.com/cfpsB4iF

An XML file that DOES work:
Warlock - http://pastebin.com/A3Fq8Lu9

Yes, I do have these in the rotation.txt, and it is in the maps folder. Here's the error message when it tries to cycle: http://pastebin.com/sWJrKHwp

**Comment by twizmwazin** [comment] 2015-02-14 15:36
Please do not use the `Download zip` button, use `git clone` to get the source. Please do that to get the latest source and then reconfirm the bug.

**Comment by Ambamore2000** [comment] 2015-02-14 16:51
Bug still occurs after using git clone instead of downloading zip.

**Comment by knightopress** [comment] 2015-02-14 17:01
[01:38:36 INFO]: World matches/b11f7667-e278-43f5-98b9-b0abe0119ba7 is a duplicate of another world and has been prevented from loading. Please delete the uid.dat file from matches/b11f7667-e278-43f5-98b9-b0abe0119ba7's world directory if you want to be able to load the duplicate world.

I think you should do what it says.

**Comment by Ambamore2000** [comment] 2015-02-14 17:11
I already did that before.

**Comment by Ambamore2000** [comment] 2015-02-14 17:12
I also want to note, when I try loading the original-CardinalPGM plugin, I get this error, http://pastebin.com/HX75NQkp.

**Comment by twizmwazin** [comment] 2015-02-14 17:14
@Ambamore2000 the `original` prefixed Cardinal is just the Cardinal classes, before the maven shade plugin is executed. It is for reference only, and should be ignored.

**Comment by Ambamore2000** [comment] 2015-02-14 17:29
Alright, found this. When I start the server, CardinalPGM first loads DeepwindJungle. The error message:
http://pastebin.com/yWCpUMtK

**Comment by twizmwazin** [comment] 2015-02-14 17:38
@Ambamore2000 I know what the issue is, I'll fix it soon

**Comment by RubeGamerV** [comment] 2015-02-14 23:28
Do not use UUID in xml to authors

**Closed** 2015-02-15 16:23 UTC
Labels: bug
