### ISSUE TITLE
observer kits don't work

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#569] opened 2015-04-09 14:59 UTC
maps like boombox or cannon duel have a obs kit that gives night vision, it works for  players that have joined, but not for observers

**Comment by SungMatt** [comment] 2015-04-09 15:06
Cardinal version please, and isn't this a duplicate of #467 ?

Also, could you show us the XML? If you are using the included Cannon Duel XML, note that the kit "obs+" does not exist.

**Comment by Pablete1234** [comment] 2015-04-09 16:07
does the kit name matter? it should be given to observers if it's stated to, in ocn  observers do get the effect

**Comment by Pablete1234** [comment] 2015-04-09 16:14
i checked the xml again, cannon duel has the spawns like this:
<default yaw="90" kit="obs+">
<cylinder base="31.5,58,37.5" radius="4" height="0"/>
</default>
so it gives the players the kit obs+, and that kit is on: house-of-core.xml
<include src="../house-of-cores.xml"/>

in HoC xml:
<kit name="obs+" parents="obs">
<potion duration="oo">night vision</potion>
</kit>

and yes, i do have HoC xml, and it's on "../house-of-core.xml"

**Comment by CaptainElliott** [comment] 2015-04-09 16:16
I fixed your XML links :)

**Comment by Pablete1234** [comment] 2015-04-09 16:57
last line of my coment: -> and yes, i do have HoC xml, and it's on "../house-of-core.xml"

**Closed** 2015-04-10 20:37 UTC
