### ISSUE TITLE
Map fails to cycle when there is no scoreboard

### ISSUE THREAD

**Issue by TeamDDG** [twizmwazin/CardinalPGM#898] opened 2015-10-03 19:39 UTC
[21:38:03] [Server thread/ERROR]: Could not pass event CycleCompleteEvent to Cardinal v1.0-SNAPSHOT-git-CardinalPGM-7532e7a
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:279) ~[bukkit.jar:git-Bukkit-bcf9cb9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[bukkit.jar:git-Bukkit-bcf9cb9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [bukkit.jar:git-Bukkit-bcf9cb9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [bukkit.jar:git-Bukkit-bcf9cb9]
	at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:56) [CardinalPGM-1.0-SNAPSHOT.jar:?]
	at in.twizmwaz.cardinal.GameHandler$1.run(GameHandler.java:36) [CardinalPGM-1.0-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) [bukkit.jar:git-Bukkit-bcf9cb9]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [bukkit.jar:git-Bukkit-bcf9cb9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:696) [bukkit.jar:git-Bukkit-bcf9cb9]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:351) [bukkit.jar:git-Bukkit-bcf9cb9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:645) [bukkit.jar:git-Bukkit-bcf9cb9]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:555) [bukkit.jar:git-Bukkit-bcf9cb9]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at in.twizmwaz.cardinal.module.modules.timeLimit.TimeLimit.getMatchWinner(TimeLimit.java:30) ~[?:?]
	at in.twizmwaz.cardinal.module.modules.scoreboard.ScoreboardModule.update(ScoreboardModule.java:155) ~[?:?]
	at in.twizmwaz.cardinal.module.modules.scoreboard.ScoreboardModule.onCycleComplete(ScoreboardModule.java:121) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:277) ~[bukkit.jar:git-Bukkit-bcf9cb9]
	... 12 more

**Comment by Prodigy4532** [comment] 2015-10-03 20:55
you are using SportBukkit or CraftBukkit?

**Comment by TeamDDG** [comment] 2015-10-03 23:07
SportBukkit-1.8.7

**Comment by twizmwazin** [comment] 2015-10-04 01:23
Use pastebin, and we need more context.

**Comment by TeamDDG** [comment] 2015-10-04 01:27
http://pastebin.com/wWnGDEBv

**Comment by twizmwazin** [comment] 2015-10-04 02:54
I'm lead to think this is an XML issue.

**Comment by TeamDDG** [comment] 2015-10-04 10:59
i got that error on all maps

**Comment by Pablete1234** [comment] 2015-10-04 14:20
[This](https://github.com/twizmwazin/CardinalPGM/blob/149d4de638b43eb42d8717a50a85adf15e256c51/src/main/java/in/twizmwaz/cardinal/module/modules/timeLimit/TimeLimit.java#L30) seems to be a NPE, so is there no match winner?

**Comment by twizmwazin** [comment] 2015-10-09 01:54
Closing as I'm pretty certain this isn't valid

**Comment by iEli2tyree011** [comment] 2015-10-09 18:45
This seems to be caused by a map that has no objectives or score, it should still work properly

**Comment by Pablete1234** [comment] 2015-10-09 19:04
@iEli2tyree011 it seems useless, if there is no objectives or score, what should happen? map should load with no scoreboard or a "invalid" scoreboard?

**Comment by iEli2tyree011** [comment] 2015-10-09 19:46
@Pablete1234 No scoreboard

**Comment by Pablete1234** [comment] 2015-11-08 04:18
@iEli2tyree011 @twizmwazin missing a bug label?

**Comment by dentmaged** [comment] 2015-11-08 16:12
I agree with @Pablete1234, why should we load maps without any objective?

**Comment by Pablete1234** [comment] 2015-11-08 17:43
@dentmaged imagine a map with FFA, ffa is not an objective ;) (when ffa is implemented, ffa will have a scoreboard etc, but for the time being, the map should atleast load)

**Comment by dentmaged** [comment] 2015-11-08 19:04
@Pablete1234 FFA has an objective; get the most kills.

**Comment by Pablete1234** [comment] 2015-11-08 19:23
@dentmaged but not ATM, since ffa is not implemented, cardinal just "doesn't know what to do with the map", and if that happens, it should just load the map and not show a scoreboard, instead of spamming the console

**Comment by Pablete1234** [comment] 2016-05-04 20:39
I think this isn't an issue anymore because of all the changes to how wins get calculated, @TeamDDG if it still is an issue, feel free to post and i'll reopen this

**Closed by Pablete1234** 2016-05-04 20:39 UTC
Labels: bug
